version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /host/lunar-sensor-bridge
    schedule:
      interval: monthly
